/**
 * A markdown table whose columns are already padded.
 *
 * Prettier aligns table columns to their widest cell. A generator that emits
 * `| a | b |` without that padding produces different bytes on every run relative
 * to `pnpm format`, so the two tools overwrite each other: the formatter reflows
 * what the generator wrote, the generator overwrites what the formatter wrote, and
 * `format:check` and the staleness gate disagree forever. Emitting the aligned
 * form is what makes the output stable under both.
 *
 * Shared rather than written twice, because a page generated by a copy of this
 * function and a page generated by the other one differ by however much padding
 * either has drifted — and the difference shows up as a red gate on a commit that
 * changed nothing.
 *
 * @param {string[]} headers
 * @param {string[][]} rows
 * @returns {string[]}
 */
export function table(headers, rows) {
  const widths = headers.map((header, column) =>
    Math.max(header.length, ...rows.map((row) => (row[column] ?? '').length)),
  );
  const line = (/** @type {string[]} */ cells) =>
    `| ${cells.map((cell, i) => cell.padEnd(widths[i] ?? 0)).join(' | ')} |`;
  return [
    line(headers),
    line(widths.map((width) => '-'.repeat(width))),
    ...rows.map((row) => line(headers.map((_header, column) => row[column] ?? ''))),
  ];
}
