#!/usr/bin/env node
/**
 * deps-policy.mjs — three questions about dependencies, run against the tree.
 *
 * Reads three files and answers three questions, none of which any existing gate
 * asked. The reasoning, and the record of the defect that motivated each question,
 * is in `scripts/lib/deps-policy.mjs`; this file is the CLI around it.
 *
 * ```
 * 1. A declared dependency that nothing imports.       unusedDependencies
 * 2. A resolved version nobody recorded a decision      compareResolvedToBaseline
 *    about.
 * 3. An `overrides` row whose review date has passed.   expiredOverrideReviews
 * ```
 *
 * ## Tier: `pr-reporting`, and what would change that
 *
 * It is `pr-reporting` on the first run because it is **red against the tree as it
 * stands** — `effect` is declared in `apps/api` and imported nowhere, and three of
 * the five `pnpm-workspace.yaml` overrides were last reviewed in June and September
 * 2026. Those are real findings, not a gate that is broken.
 *
 * So it reports first, the findings become ledger rows, and the tier moves to
 * `pr-blocking` in a later commit with the measurements behind it — the same
 * evidence-then-raise order the plan of record's standing rule 2 states, and the
 * same order `security:static` is waiting on.
 *
 * ## The baseline has no writer, deliberately
 *
 * `coverage:baseline` and `complexity:baseline` write their files, because they
 * record **measurements** — a number a machine can take. This file records
 **decisions**: that a human read a release note and accepted this version. A
 * `--write` flag would let the file be regenerated by the same run that is supposed
 * to judge it, which is the "make the gate agree with the tree instead of with the
 * code" failure `scripts/gate-tooling.json` names for the other baseline writers.
 *
 * `--print-baseline` exists and only prints. Generating the first copy of the file
 * is a one-off, and the rows it prints are proposals until someone edits them in.
 *
 * ## Exit codes
 *
 * `0` nothing found · `1` findings · `2` a file this gate needs is missing or
 * unreadable, which is not a pass.
 */

import { existsSync, readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';

import {
  compareResolvedToBaseline,
  expiredOverrideReviews,
  isConfigurationFile,
  parseLockfile,
  unusedDependencies,
} from './lib/deps-policy.mjs';

const repoRoot = path.resolve(import.meta.dirname, '..');
const LOCKFILE = path.join(repoRoot, 'pnpm-lock.yaml');
const WORKSPACE = path.join(repoRoot, 'pnpm-workspace.yaml');
const BASELINE = path.join(repoRoot, 'docs', 'quality', 'dependency-baseline.json');

/** Directories that hold no workspace source and would only slow the scan. */
const SKIP_DIRECTORIES = new Set([
  '.git',
  '.kilo',
  '.omo',
  '.sisyphus',
  '.turbo',
  'coverage',
  'dist',
  'node_modules',
  'test-results',
  'var',
]);

/** The file extensions that can contain an import statement. */
const SOURCE_EXTENSIONS = /\.(ts|tsx|mts|cts|js|mjs|cjs)$/;

/**
 * @typedef {object} DepsPolicyReport
 * @property {{ name: string, declaredIn: string[] }[]} unused
 * @property {{ name: string, version: string }[]} unreviewed
 * @property {{ name: string, version: string }[]} stale
 * @property {{ name: string, reviewed: string, resolved: string }[]} changed
 * @property {{ override: string, reviewedOn: string | null }[]} expiredOverrides
 */

/**
 * Read a file the gate cannot proceed without.
 *
 * @param {string} file
 * @returns {string}
 */
function read(file) {
  if (!existsSync(file)) {
    throw new Error(
      `deps-policy: ${path.relative(repoRoot, file)} is missing. This gate compares the tree ` +
        'against that file; without it there is nothing to compare against, and reporting ' +
        'nothing would be the fail-open direction.',
    );
  }
  return readFileSync(file, 'utf8');
}

/**
 * Every source file under a directory, split into application source and configuration.
 *
 * Split rather than concatenated because the two are read differently: an import means
 * the same thing in both, and a quoted package name means a dependency only in
 * configuration. One string per side, so the matcher runs once per dependency rather
 * than once per dependency per file.
 *
 * @param {string} directory
 * @returns {{ source: string, configuration: string }}
 */
function scanText(directory) {
  /** @type {string[]} */
  const source = [];
  /** @type {string[]} */
  const configuration = [];
  /** @param {string} current */
  const walk = (current) => {
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      if (SKIP_DIRECTORIES.has(entry.name)) continue;
      const full = path.join(current, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (SOURCE_EXTENSIONS.test(entry.name)) {
        const text = readFileSync(full, 'utf8');
        (isConfigurationFile(full, repoRoot) ? configuration : source).push(text);
      }
    }
  };
  walk(directory);
  return { source: source.join('\n'), configuration: configuration.join('\n') };
}

/**
 * Run all three checks.
 *
 * @param {string} today ISO date, so the caller controls the clock.
 * @returns {DepsPolicyReport}
 */
export function collect(today) {
  const parsed = parseLockfile(read(LOCKFILE));
  const baseline = parseBaseline();
  const exemptions = toolExemptions(baseline);
  const documented = documentedUnused(baseline).map((row) => row.name);
  /** @type {Record<string, string>} */
  const resolved = {};

  for (const groups of Object.values(parsed.importers)) {
    for (const group of Object.values(groups)) {
      for (const [name, entry] of Object.entries(group)) {
        // A workspace link resolves to a path, not a registry version, so there is
        // no version here for a human to have reviewed.
        if (entry.version.startsWith('link:')) continue;
        resolved[name] = entry.version;
      }
    }
  }

  // The unused check reads the whole repository's source once, whatever an importer
  // is: a package's dependency is declared by that package, but a root dependency can
  // legitimately be imported by a gate script or by `e2e/`, and a per-package index
  // would report every one of those as unused. The importer is still recorded on each
  // finding, because that is where the declaration has to be fixed.
  const scan = scanText(repoRoot);
  return {
    unused: unusedDependencies(parsed, scan.source, exemptions, documented, scan.configuration),
    ...compareResolvedToBaseline(resolved, baseline),
    expiredOverrides: expiredOverrideReviews(read(WORKSPACE), today),
  };
}

/**
 * The dependencies the baseline exempts, keyed by importer with `*` for all of them.
 *
 * A tool dependency is invoked, never imported: `typescript` by `tsc`, `eslint` by
 * the lint script, `vitest` by the test runner. Naming them is a decision, so it
 * lives in the reviewed file rather than inside the checker — a name hard-coded in a
 * checker is a second authority nobody reviews.
 *
 * @param {unknown} baseline
 * @returns {Record<string, string[]>}
 */
function toolExemptions(baseline) {
  const record = /** @type {Record<string, unknown>} */ (
    typeof baseline === 'object' && baseline !== null ? baseline : {}
  );
  /** @type {Record<string, string[]>} */
  const exemptions = {};
  const tools = record.invokedAsTools;
  if (typeof tools !== 'object' || tools === null) return exemptions;
  for (const [importer, names] of Object.entries(tools)) {
    if (!Array.isArray(names)) continue;
    exemptions[importer] = names.filter((name) => typeof name === 'string');
  }
  return exemptions;
}

/**
 * The dependencies a human has recorded as deliberately unused, and the reasons.
 *
 * `ajv` in `packages/shared-contracts` is the one at HEAD: that package's own README
 * says it is "installed and unused" for a capability the register marks not shipped.
 * Removing it is a product decision about that capability, so the reason is recorded
 * beside it rather than deleted by a linter.
 *
 * @param {unknown} baseline
 * @returns {{ name: string, reason: string }[]}
 */
function documentedUnused(baseline) {
  const record = /** @type {Record<string, unknown>} */ (
    typeof baseline === 'object' && baseline !== null ? baseline : {}
  );
  const documented = record.documentedButUnused;
  if (typeof documented !== 'object' || documented === null) return [];
  return Object.entries(documented).map(([name, reason]) => ({
    name,
    reason: typeof reason === 'string' ? reason : '',
  }));
}

/** @type {unknown} */
let cachedBaseline = null;

/**
 * The baseline file, read once.
 *
 * Typed as `unknown` on purpose. The parsed shape is validated where it is used —
 * `compareResolvedToBaseline` refuses a file it cannot read, the two helpers above
 * walk it defensively — so nothing here casts JSON into a shape it has not checked.
 *
 * @returns {unknown}
 */
function parseBaseline() {
  if (cachedBaseline === null) cachedBaseline = JSON.parse(read(BASELINE));
  return cachedBaseline;
}

/**
 * The rows a first-time baseline would carry, printed and not written.
 *
 * @returns {{ name: string, version: string, declaredIn: string[] }[]}
 */
export function proposedBaselineRows() {
  const parsed = parseLockfile(read(LOCKFILE));
  /** @type {Map<string, { version: string, declaredIn: Set<string> }>} */
  const rows = new Map();
  for (const [importer, groups] of Object.entries(parsed.importers)) {
    for (const group of Object.values(groups)) {
      for (const [name, entry] of Object.entries(group)) {
        if (entry.version.startsWith('link:')) continue;
        const existing = rows.get(name);
        if (existing) existing.declaredIn.add(importer);
        else rows.set(name, { version: entry.version, declaredIn: new Set([importer]) });
      }
    }
  }
  return [...rows.entries()]
    .map(([name, row]) => ({
      name,
      version: row.version,
      declaredIn: [...row.declaredIn].sort(),
    }))
    .sort((left, right) => left.name.localeCompare(right.name));
}

/**
 * @param {DepsPolicyReport} report
 * @returns {string}
 */
function format(report) {
  const lines = ['Dependency policy', ''];
  const section = (/** @type {string} */ title, /** @type {string[]} */ rows) => {
    if (rows.length === 0) return;
    lines.push(`${title} (${rows.length})`);
    lines.push(...rows.map((row) => `  ${row}`));
    lines.push('');
  };

  section(
    'Declared but never referenced',
    report.unused.map((row) => `${row.name} — declared by ${row.declaredIn.join(', ')}`),
  );
  section(
    'Resolved but never reviewed',
    report.unreviewed.map((row) => `${row.name}@${row.version}`),
  );
  section(
    'Recorded but no longer resolved',
    report.stale.map((row) => `${row.name}@${row.version}`),
  );
  section(
    'Resolved version differs from the recorded one',
    report.changed.map((row) => `${row.name} ${row.reviewed} → ${row.resolved}`),
  );
  section(
    'Overrides past their review date',
    report.expiredOverrides.map((row) =>
      row.reviewedOn === null
        ? `${row.override} — no review date recorded`
        : `${row.override} — reviewed ${row.reviewedOn}`,
    ),
  );

  if (lines.length === 2) lines.push('Nothing to report.');
  return lines.join('\n');
}

/**
 * @param {string[]} argv
 * @returns {number}
 */
export function main(argv) {
  if (argv.includes('--print-baseline')) {
    console.log(JSON.stringify({ entries: proposedBaselineRows() }, null, 2));
    return 0;
  }
  if (argv.includes('--json')) {
    console.log(JSON.stringify(collect(new Date().toISOString().slice(0, 10)), null, 2));
    return 0;
  }

  const report = collect(new Date().toISOString().slice(0, 10));
  console.log(format(report));
  const findings =
    report.unused.length +
    report.unreviewed.length +
    report.stale.length +
    report.changed.length +
    report.expiredOverrides.length;
  return findings === 0 ? 0 : 1;
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(import.meta.filename)) {
  try {
    process.exitCode = main(process.argv.slice(2));
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 2;
  }
}
