# docker-smoke.ps1 — Docker smoke harness for Windows PowerShell
# Usage:
#   .\scripts\docker-smoke.ps1 --prepare-env-only
#   .\scripts\docker-smoke.ps1 --dry-run
#   .\scripts\docker-smoke.ps1

param([string]$Mode = "")

$RepoRoot = Split-Path -Parent $PSScriptRoot
$EnvDir = Join-Path $RepoRoot ".sisyphus\tmp\production-readiness"
$EnvFile = Join-Path $EnvDir ".env.test"
$ComposeProject = "automate-smoke-test"

New-Item -ItemType Directory -Force -Path $EnvDir | Out-Null
@"
# GENERATED BY scripts/docker-smoke.ps1 — TEST VALUES ONLY — NOT FOR PRODUCTION
DATABASE_URL=postgres://automate:test-pg-password-for-ci-smoke-32chars!@postgres:5432/automate
POSTGRES_PASSWORD=test-pg-password-for-ci-smoke-32chars!
PORT=3000
CORS_ORIGIN=http://localhost:5173
COOKIE_SECRET=test-cookie-secret-for-ci-smoke-32plus-chars!!
REPORTER_SECRET=test-reporter-secret-16plus!!
AUTOMATE_SERVICE_SECRET=test-service-secret-for-ci-32chars!!
AUTOMATE_API_KEY=test-api-key-for-ci-smoke-16plus!!
VAULT_SECRET=test-vault-secret-for-ci-smoke-min-32chars!!
AUTOMATE_DASHBOARD_API_KEY=test-dashboard-api-key-for-ci-smoke!!
"@ | Set-Content -Path $EnvFile -Encoding UTF8

Write-Host "[docker-smoke] Generated env file: $EnvFile"

if ($Mode -eq "--prepare-env-only") {
    Write-Host "[docker-smoke] --prepare-env-only: env file created, exiting."
    exit 0
}

$ComposeCmd = "docker compose -f `"$RepoRoot\docker-compose.unified.yml`" --project-name $ComposeProject --env-file `"$EnvFile`" up api web postgres -d --wait"

if ($Mode -eq "--dry-run") {
    Write-Host "[docker-smoke] --dry-run: would run:"
    Write-Host "  $ComposeCmd"
    exit 0
}

Write-Host "[docker-smoke] Starting unified stack..."
Invoke-Expression $ComposeCmd

Write-Host "[docker-smoke] Checking API health..."
Invoke-WebRequest -UseBasicParsing -Uri "http://localhost:3100/health" | Out-Null
Write-Host "[docker-smoke] Checking web root..."
Invoke-WebRequest -UseBasicParsing -Uri "http://localhost:5173/" | Out-Null

Write-Host "[docker-smoke] Tearing down..."
docker compose -f "$RepoRoot\docker-compose.unified.yml" --project-name "$ComposeProject" down -v

Write-Host "[docker-smoke] Done."
