#!/usr/bin/env bash
# docker-smoke.sh — Docker smoke harness for unified platform
# Usage:
#   ./scripts/docker-smoke.sh --prepare-env-only  # Create env file, do not run compose
#   ./scripts/docker-smoke.sh --dry-run            # Print compose command, do not run
#   ./scripts/docker-smoke.sh                      # Run full smoke test
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_DIR="$REPO_ROOT/.sisyphus/tmp/production-readiness"
ENV_FILE="$ENV_DIR/.env.test"
COMPOSE_PROJECT="automate-smoke-test"

mkdir -p "$ENV_DIR"
cat > "$ENV_FILE" <<'ENVEOF'
# GENERATED BY scripts/docker-smoke.sh — TEST VALUES ONLY — NOT FOR PRODUCTION
DATABASE_URL=postgres://automate:test-pg-password-for-ci-smoke-32chars!@postgres:5432/automate
POSTGRES_PASSWORD=test-pg-password-for-ci-smoke-32chars!
PORT=3000
CORS_ORIGIN=http://localhost:5173
COOKIE_SECRET=test-cookie-secret-for-ci-smoke-32plus-chars!!
REPORTER_SECRET=test-reporter-secret-16plus!!
AUTOMATE_SERVICE_SECRET=test-service-secret-for-ci-32chars!!
AUTOMATE_API_KEY=test-api-key-for-ci-smoke-16plus!!
VAULT_SECRET=test-vault-secret-for-ci-smoke-min-32chars!!
AUTOMATE_DASHBOARD_API_KEY=test-dashboard-api-key-for-ci-smoke!!
ENVEOF

echo "[docker-smoke] Generated env file: $ENV_FILE"

case "${1:-}" in
  --prepare-env-only)
    echo "[docker-smoke] --prepare-env-only: env file created, exiting."
    exit 0
    ;;
esac

COMPOSE_CMD="docker compose -f $REPO_ROOT/docker-compose.unified.yml --project-name $COMPOSE_PROJECT --env-file $ENV_FILE up api web postgres -d --wait"

case "${1:-}" in
  --dry-run)
    echo "[docker-smoke] --dry-run: would run:"
    echo "  $COMPOSE_CMD"
    exit 0
    ;;
esac

echo "[docker-smoke] Starting unified stack..."
eval "$COMPOSE_CMD"

echo "[docker-smoke] Checking API health..."
curl -sf http://localhost:3100/health
echo "[docker-smoke] Checking web root..."
curl -sf http://localhost:5173/

echo "[docker-smoke] Tearing down..."
docker compose -f "$REPO_ROOT/docker-compose.unified.yml" --project-name "$COMPOSE_PROJECT" down -v

echo "[docker-smoke] Done."
