/**
 * `pnpm status:10` — the twelve points, each with a verdict and a reason.
 *
 * **`status:10` is a gate now, and it exits non-zero on a `fail` row.** It was a
 * measurement until 2026-10-01, when the last `fail` — point 3, the missing
 * durable-path spec — was closed by writing the artefact rather than by reclassifying
 * the clause. The graduation was the reason `--strict` existed as a switch: a gate that
 * reports red forever is not a gate, so arming it was a deliberate act rather than a
 * default. The reasoning is at the `strict` constant below.
 *
 * **It covers exactly what it can read.** Twelve `not_configured` rows are unaffected,
 * because this script reads committed files and executes no gate; each names the command
 * that would decide it.
 *
 * Read-only. It reads the tree, prints a table, and writes to the GitHub job
 * summary when one is set. `--json` is for a caller that wants the structure rather
 * than the prose; the site page is generated by `pnpm site:generate` rather than
 * here, so that a page can never be a snapshot of a moment this script happened to
 * observe — the staleness gate in `docs:check` compares the committed page against
 * a fresh run of the generator, and a page written by the reporter would satisfy
 * that gate by construction.
 */
import { appendFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { evaluate, loadContext, markdownTable, repoRoot, tally } from './lib/status-ten.mjs';

const root = repoRoot();
const reports = evaluate(loadContext(root));
const counts = tally(reports);

/**
 * **`--strict` graduated on 2026-10-01**, in the commit that made the fails zero.
 *
 * The switch existed because a gate that reports red forever is not a gate: it blocks
 * every pull request and teaches reviewers to read red as noise, which is exactly what
 * `test:render` did by shipping `pr-blocking` with no baseline. The remedy was not to
 * remove the gate but to refuse to arm it before the table was green — so the arming
 * was the recorded, deliberate act it needed to be.
 *
 * The condition is met and the arming is unconditional now. Point 3 was the last
 * `fail`, and it was closed by writing `e2e/product/durable-path.spec.ts` — a real
 * artefact, not a reclassification — with a `playwright.config.ts` project of its own so
 * it cannot become a green no-op. `scripts/lib/status-ten.test.mjs` asserts every stage
 * marker is present **in that file**, so the point cannot go back to passing on a spec
 * that exists and names nothing.
 *
 * **What `--strict` does and does not cover.** It fails on a `fail` row. It does not
 * touch the twelve `not_configured` rows, and it cannot: `status:10` reads committed
 * files and executes no gate, so a claim whose proof is a run is unmeasured here by
 * construction. Each of those twelve names the command that would decide it. Arming the
 * switch asserts that nothing the script *can* read is failing — which is the whole of
 * what this script knows.
 *
 * The flag is kept as an accepted no-op so the documented graduation step and any
 * workflow already passing it keep working, rather than being broken by the commit that
 * made them unnecessary.
 */
const strict = true;

if (process.argv.includes('--json')) {
  console.log(JSON.stringify({ counts, points: reports }, null, 2));
} else {
  console.log("Automate — 10/10, as the roadmap's §17 defines it");
  console.log('');
  for (const report of reports) {
    console.log(
      `${String(report.number).padStart(2)}. ${report.verdict.padEnd(15)} ${report.title}`,
    );
    for (const clause of report.clauses) {
      if (clause.verdict === 'pass') continue;
      console.log(`      ${clause.verdict.padEnd(15)} ${clause.claim}`);
      console.log(`      ${' '.repeat(15)} ${clause.reason}`);
    }
  }
  console.log('');
  console.log(
    `${String(counts.pass)} pass · ${String(counts.fail)} fail · ` +
      `${String(counts.not_configured)} not_configured`,
  );
  console.log('');
  console.log(
    'A `not_configured` row is a legitimate state: not checked, with the reason above and',
  );
  console.log('the command that would check it. It is not a pass, and it is not hidden.');
  console.log('The definition of done this repository can state honestly is zero `fail` rows.');
  console.log('');
  console.log(markdownTable(reports).join('\n'));
  writeSummary();
}

if (strict && counts.fail > 0) {
  console.error(
    `status:10: ${String(counts.fail)} point(s) fail. Either close them, or record a ` +
      '`debt` row with an owner and a removal condition for the ones that are being deferred.',
  );
  process.exit(1);
}

/**
 * The same table in the job summary.
 *
 * A gate whose number exists only in a scrollback buffer is a number nobody reads,
 * and the twelve rows are the artifact this whole script exists to produce. Guarded
 * on the variable existing rather than truthy, because `GITHUB_STEP_SUMMARY` is a
 * path and an empty one is a configuration error worth a stack trace.
 */
function writeSummary() {
  const summaryPath = process.env['GITHUB_STEP_SUMMARY'];
  if (!summaryPath || !existsSync(summaryPath)) return;
  appendFileSync(
    summaryPath,
    [
      '### 10/10, measured',
      '',
      'Roadmap §17, one verdict per point. `not_configured` is a state, not a pass.',
      '',
      ...markdownTable(reports),
      '',
      `**${String(counts.pass)} pass · ${String(counts.fail)} fail · ${String(counts.not_configured)} not_configured**`,
      '',
      'Reproduce with `pnpm status:10`. Every row names the command that decides it.',
      '',
    ].join('\n'),
    'utf8',
  );
  console.log(`job summary written to ${path.relative(root, summaryPath)}`);
}
