/**
 * `pnpm status:10` — the twelve points, each with a verdict and a reason.
 *
 * **This is a measurement, not a gate, and the exit code says so.** It exits 0
 * whatever the verdicts are. A measurement that fails the build is a gate, and a
 * gate needs a budget decision (D6), a tier, and a reason to be red; none of those
 * exist for a list that has not been read yet, and the first version of this
 * repository's instinct on that subject — `test:render` shipped `pr-blocking` with
 * no baseline — is the mistake this file is shaped to avoid.
 *
 * `--strict` is the graduation switch, and it is not a default because turning it
 * on while the table still has `fail` rows would make a required check that can
 * never pass, which blocks every pull request and teaches reviewers to read red as
 * noise. Graduate it when the fails are zero, in the same commit that makes them
 * zero, and record the reason in `scripts/gate-tooling.json` the way
 * `render-gate-phase.mjs` records the rendering gate's.
 *
 * Read-only. It reads the tree, prints a table, and writes to the GitHub job
 * summary when one is set. `--json` is for a caller that wants the structure rather
 * than the prose; the site page is generated by `pnpm site:generate` rather than
 * here, so that a page can never be a snapshot of a moment this script happened to
 * observe — the staleness gate in `docs:check` compares the committed page against
 * a fresh run of the generator, and a page written by the reporter would satisfy
 * that gate by construction.
 */
import { appendFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { evaluate, loadContext, markdownTable, repoRoot, tally } from './lib/status-ten.mjs';

const root = repoRoot();
const reports = evaluate(loadContext(root));
const counts = tally(reports);
const strict = process.argv.includes('--strict');

if (process.argv.includes('--json')) {
  console.log(JSON.stringify({ counts, points: reports }, null, 2));
} else {
  console.log("Automate — 10/10, as the roadmap's §17 defines it");
  console.log('');
  for (const report of reports) {
    console.log(
      `${String(report.number).padStart(2)}. ${report.verdict.padEnd(15)} ${report.title}`,
    );
    for (const clause of report.clauses) {
      if (clause.verdict === 'pass') continue;
      console.log(`      ${clause.verdict.padEnd(15)} ${clause.claim}`);
      console.log(`      ${' '.repeat(15)} ${clause.reason}`);
    }
  }
  console.log('');
  console.log(
    `${String(counts.pass)} pass · ${String(counts.fail)} fail · ` +
      `${String(counts.not_configured)} not_configured`,
  );
  console.log('');
  console.log(
    'A `not_configured` row is a legitimate state: not checked, with the reason above and',
  );
  console.log('the command that would check it. It is not a pass, and it is not hidden.');
  console.log('The definition of done this repository can state honestly is zero `fail` rows.');
  console.log('');
  console.log(markdownTable(reports).join('\n'));
  writeSummary();
}

if (strict && counts.fail > 0) {
  console.error(
    `status:10 --strict: ${String(counts.fail)} point(s) fail. Either close them, or record a ` +
      '`debt` row with an owner and a removal condition for the ones that are being deferred.',
  );
  process.exit(1);
}

/**
 * The same table in the job summary.
 *
 * A gate whose number exists only in a scrollback buffer is a number nobody reads,
 * and the twelve rows are the artifact this whole script exists to produce. Guarded
 * on the variable existing rather than truthy, because `GITHUB_STEP_SUMMARY` is a
 * path and an empty one is a configuration error worth a stack trace.
 */
function writeSummary() {
  const summaryPath = process.env['GITHUB_STEP_SUMMARY'];
  if (!summaryPath || !existsSync(summaryPath)) return;
  appendFileSync(
    summaryPath,
    [
      '### 10/10, measured',
      '',
      'Roadmap §17, one verdict per point. `not_configured` is a state, not a pass.',
      '',
      ...markdownTable(reports),
      '',
      `**${String(counts.pass)} pass · ${String(counts.fail)} fail · ${String(counts.not_configured)} not_configured**`,
      '',
      'Reproduce with `pnpm status:10`. Every row names the command that decides it.',
      '',
    ].join('\n'),
    'utf8',
  );
  console.log(`job summary written to ${path.relative(root, summaryPath)}`);
}
