import React from 'react';
import ReactDOM from 'react-dom/client';
import { RouterProvider, createRouter } from '@tanstack/react-router';
import { QueryClientProvider } from '@tanstack/react-query';
import { Toaster } from 'sonner';
import * as Sentry from '@sentry/react';
import { useThemeStore, applyTheme } from '@/store/themeStore';
import './index.css';
import './lib/i18n';
import { queryClient } from '@/lib/queryClient';

// Auto-generated by TanStack Router Vite plugin
import { routeTree } from './routeTree.gen';

// Initialize Sentry before createRoot so startup errors are captured (ERR-01)
// enabled: false when VITE_SENTRY_DSN is not set — zero overhead in local dev
Sentry.init({
  dsn: import.meta.env.VITE_SENTRY_DSN,
  environment: import.meta.env.MODE,
  integrations: [
    Sentry.browserTracingIntegration(),
    Sentry.replayIntegration({ maskAllText: false, blockAllMedia: false }),
  ],
  tracesSampleRate: import.meta.env.PROD ? 0.1 : 1.0,
  replaysOnErrorSampleRate: 1.0,
  replaysSessionSampleRate: 0.0,
  enabled: !!import.meta.env.VITE_SENTRY_DSN,
});


const router = createRouter({
  routeTree,
  context: { queryClient },
  defaultPreload: 'intent',
  defaultPreloadStaleTime: 0,
});

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}


// Apply persisted theme before first paint to avoid flash
applyTheme(useThemeStore.getState().theme);

// Listen for OS preference changes when in 'system' mode
window.matchMedia('(prefers-color-scheme: light)').addEventListener('change', () => {
  if (useThemeStore.getState().theme === 'system') {
    applyTheme('system');
  }
});

// React 19 error hooks — replaces componentDidCatch at the root level (ERR-04)
ReactDOM.createRoot(document.getElementById('root')!, {
  onUncaughtError: Sentry.reactErrorHandler(),
  onCaughtError: Sentry.reactErrorHandler(),
}).render(
  <React.StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
      <Toaster
        position="bottom-right"
        richColors
        toastOptions={{
          classNames: {
            toast: 'glass-toast border border-white/10',
            title: 'text-sm font-medium',
            description: 'text-xs text-secondary',
          },
        }}
      />
    </QueryClientProvider>
  </React.StrictMode>,
);
